'''
Created on May 4, 2018

@author: Rishabh Bakshi
'''

import time

from selenium import webdriver
from selenium.common.exceptions import UnexpectedAlertPresentException
from selenium.webdriver.common.keys import Keys
from datetime import datetime


# driver = webdriver.Firefox(executable_path='<Path>/geckodriver.exe')
# This block of code is used to block the notification popup which is generated by site
options = webdriver.ChromeOptions()
options.add_argument("--disable-notifications")

# to open chrome webbrowser and maximize the window
# driver = webdriver.Chrome(executable_path="<Path>/chromedriver_win32/chromedriver.exe", chrome_options=options)
# driver = webdriver.PhantomJS("C:/Users/ngduc/Downloads/phantomjs-2.1.1-windows/phantomjs-2.1.1-windows/bin/phantomjs.exe")
driver = webdriver.Chrome(executable_path="C:/Users/ngduc/Downloads/chromedriver_win32/chromedriver.exe",options=options)
# driver.maximize_window()

# Implicit Wait when element is taking time to load
driver.implicitly_wait(20)

# Connect to steam sale
# driver.get("https://www.whenisthenextsteamsale.com/")
# sale_title = driver.find_element_by_xpath("//*[@id=\"nextSale\"]")
# sale_date = driver.find_element_by_xpath("//*[@id=\"saleDate\"]")
# sale_title = sale_title.text
# sale_date = sale_date.text
# print(sale_title)
# print(sale_date)

driver.get("https://www.messenger.com/t/994597937304071")

# Login to Facebook
driver.find_element_by_id("email").clear()
driver.find_element_by_id("email").send_keys("kybiukybiu@gmail.com")
driver.find_element_by_id("pass").clear()
driver.find_element_by_id("pass").send_keys("skynet20152020")
driver.find_element_by_id("loginbutton").click()

all_message = []
now = datetime.now()

while True:
    allow_response = False
    print(allow_response)
    current_time_minute = now.strftime("%M")
    current_time_hour = now.strftime("%H")
    for i in range(int(current_time_minute)-2,int(current_time_minute)+1):
        try:
            minute = str(i)
            if len(minute) == 1:
                minute = "0" + minute
            print("//div[@data-tooltip-content=\"" + current_time_hour + ":" + minute + "\"]//span[@class=\"_3oh- _58nk\"]")
            message = driver.find_element_by_xpath("//div[@data-tooltip-content=\""+current_time_hour+":"+minute+"\"]//span[@class=\"_3oh- _58nk\"]")
            message = message.text
            if message == "hey next sale":
                print("found it")
                allow_response = True
                print(allow_response)
                break
            break
        except:
            continue
    if allow_response:
        driver.find_element_by_xpath("//div[contains(@class,'_5rpu') and @role='combobox']").send_keys("ok" + Keys.ENTER)
        driver.find_element_by_xpath("//div[contains(@class,'_5rpu') and @role='combobox']").send_keys("Next: Summer Sale" + Keys.ENTER)
        driver.find_element_by_xpath("//div[contains(@class,'_5rpu') and @role='combobox']").send_keys("June 24, 2020" + Keys.ENTER)
        time.sleep(5)
    # break


# driver.find_element_by_xpath("//div[contains(@class,'_5rpu') and @role='combobox']").send_keys("ok"+Keys.ENTER)
# driver.find_element_by_xpath("//div[contains(@class,'_5rpu') and @role='combobox']").send_keys(sale_title+Keys.ENTER)
# driver.find_element_by_xpath("//div[contains(@class,'_5rpu') and @role='combobox']").send_keys(sale_date+Keys.ENTER)



# To close the browser
driver.quit()